# resource "local_file" "pet" {
#     filename = "/home/fahad/pets.txt"
#     content = "We love pets"
#     file_permission = "0700"
# }

# resource "random_pet" "my_pet"{
#     prefix = "Mr"
#     separator = "."
#     length = "1"
#}


# resource "local_file" "pet" {
#     filename = var.filename
#     content = var.content
#     file_permission = var.file_permission
# }

# resource "random_pet" "my_pet"{
#     prefix = var.prefix
#     separator =var.separator
#     length = var.length
# }



####################### Resource Attribute

# resource "local_file" "pet" {
#     filename = var.filename
#     content = "I love my ${random_pet.my_pet.id} pet"
#     file_permission = var.file_permission
# }

# resource "random_pet" "my_pet"{
#     prefix = var.prefix
#     separator =var.separator
#     length = var.length
# }


####################### Resource dependency

resource "local_file" "pet" {
    filename = var.filename
    content = "I love my ${random_pet.my_pet.id} pet"
    file_permission = var.file_permission
    depends_on = [
        random_pet.my_pet
    ]
}

resource "random_pet" "my_pet"{
    prefix = var.prefix
    separator =var.separator
    length = var.length
}


############ Output Variable

output pet_name {
  value       = random_pet.my_pet
  description = "Record of the value of pet ID generated by random_pet resiource"
}


####################### Life Cycle Rules

########### Rule 1 #############
resource "local_file" "pet" {
    filename = var.filename
    content = "I love my ${random_pet.my_pet.id} pet"
    file_permission = var.file_permission
    
    lifecycle {
        create_before_destroy = true
    }
}


########### Rule 2 #############
resource "local_file" "pet" {
    filename = var.filename
    content = "I love my ${random_pet.my_pet.id} pet"
    file_permission = var.file_permission
    
    lifecycle {
        prevent_destroy = true
    }
}

########### Rule 3 #############
resource "aws_instance" "webserver" {
    ami = "ami-0987544"
    instance_type = "t2.micro"
    tags = {
        Name = ProjectA-Webserver
    }

    lifecycle {
        ignore_changes = all
        ignore_changes = [
            tags, ami
        ]
        ignore_changes = [
            tags
        ]
    }
}


#################### Data Sources

resource "local_file" "my_pet" {
    filename = "/home/fahad/pets.txt"
    content = data.local_file.dog.content
}


data "local_file" "dog" {
    filename = "/home/fahad/dog.txt"
}



############## Meta Arguments

### Count

resource "local_file" "CountArgument" {
    filename = var.MetaArgu
    Count = 3
}

resource "local_file" "CountArgument" {
    filename = var.MetaArgu2[count.index]
    Count = 3                                   # Hardcoated value
}

resource "local_file" "CountArgument" {
    filename = var.MetaArgu2[count.index]
    Count = length(var.MetaArgu2)                # Dynamic Value
}


##### For Each

resource "local_file" "ForEach" {
    filename = each.value
    for_each = var.foreachvar 
}

resource "local_file" "ForEach2" {
    filename = each.value
    for_each = toset(var.foreachvar2)
}

output "foreach" {
  value       = local_file.ForEach
}

